/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "gradle-lab1"
include("app", "model")

//more information
//https://github.com/gradle/dpeuni-gradle-remote-caching/tree/main?tab=readme-ov-file

val isCiServer = System.getenv().containsKey("CI")
buildCache {
    local{
        isEnabled = false
    }
    remote<HttpBuildCache> {
        // change the url to develocity
        url = uri("http://localhost:8080")
        isPush = isCiServer

        credentials {
//            username = "admin"
//            password = "admin"
            username = System.getProperty("CACHE_USERNAME")
            password = System.getProperty("CACHE_PASSWORD")
        }
    }
}
